--BASE DE DADOS DE UMA APLICAÇÃO QUE GERE EVENTOS
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS AttendEvent;
DROP TABLE IF EXISTS Comentario;
DROP TABLE IF EXISTS EventType;

-- TABLE USER

CREATE TABLE User(
	idUser INTEGER PRIMARY KEY,
	username NVARCHAR2(20) NOT NULL,
	password NVARCHAR2 NOT NULL,
	name NVARCHAR2(50) NOT NULL,
	email NVARCHAR2(50) NOT NULL
);

-- TABLE EVENT

CREATE TABLE Event(
	idEvent INTEGER PRIMARY KEY,
	idUser INTEGER REFERENCES User(idUser),
	name NVARCHAR2(50) NOT NULL,
	image NVARCHAR2(500),
	eventDate DATE,
	startHour TIME,
	description NVARCHAR2(250),
	local NVARCHAR2(100) NOT NULL,
	partyType NVARCHAR2(20) NOT NULL,
	type NVARCHAR2(20) NOT NULL,
	CHECK (type = 'public' OR type = 'private')
);

CREATE TABLE AttendEvent(
	idEvent INTEGER,
	idUser INTEGER,
	attend NVARCHAR2(20),
	PRIMARY KEY (idEvent, idUser),
	FOREIGN KEY (idEvent) REFERENCES Event(idEvent) ON DELETE CASCADE,
	FOREIGN KEY (idUser) REFERENCES User(idUser) ON DELETE CASCADE,
	CHECK (attend = 'yes' OR attend = 'no')
);

CREATE TABLE Comentario(
	idComentario INTEGER PRIMARY KEY,
	idUser INTEGER REFERENCES User(idUser),
	idEvent INTEGER REFERENCES Event(idEvent),
	comentario NVARCHAR2(200)
);


CREATE TRIGGER AttendAuto AFTER INSERT ON Event FOR EACH ROW
BEGIN
INSERT INTO AttendEvent VALUES(New.idEvent,New.idUser,"yes");
END;

	